"""update_student_profile_with_all_form_fields

Revision ID: 16348e50a45d
Revises: b1ce75b13f84
Create Date: 2025-10-09 21:16:47.216883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16348e50a45d'
down_revision: Union[str, Sequence[str], None] = 'b1ce75b13f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('email', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('date_of_birth', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('address_line2', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('willing_to_relocate', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('relocation_states', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('student_profiles', sa.Column('culinary_class_years', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('currently_employed', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('current_hours_per_week', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('previous_employment', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('previous_employer', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('previous_position', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('previous_hours_per_week', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('transportation', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('hours_per_week', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('availability', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('student_profiles', sa.Column('weekend_availability', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('ready_to_work', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('available_date', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('has_resume', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('resume_url', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('has_food_handlers_card', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('food_handlers_card_url', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('has_servsafe', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('interests', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'interests')
    op.drop_column('student_profiles', 'has_servsafe')
    op.drop_column('student_profiles', 'food_handlers_card_url')
    op.drop_column('student_profiles', 'has_food_handlers_card')
    op.drop_column('student_profiles', 'resume_url')
    op.drop_column('student_profiles', 'has_resume')
    op.drop_column('student_profiles', 'available_date')
    op.drop_column('student_profiles', 'ready_to_work')
    op.drop_column('student_profiles', 'weekend_availability')
    op.drop_column('student_profiles', 'availability')
    op.drop_column('student_profiles', 'hours_per_week')
    op.drop_column('student_profiles', 'transportation')
    op.drop_column('student_profiles', 'previous_hours_per_week')
    op.drop_column('student_profiles', 'previous_position')
    op.drop_column('student_profiles', 'previous_employer')
    op.drop_column('student_profiles', 'previous_employment')
    op.drop_column('student_profiles', 'current_hours_per_week')
    op.drop_column('student_profiles', 'currently_employed')
    op.drop_column('student_profiles', 'culinary_class_years')
    op.drop_column('student_profiles', 'relocation_states')
    op.drop_column('student_profiles', 'willing_to_relocate')
    op.drop_column('student_profiles', 'address_line2')
    op.drop_column('student_profiles', 'date_of_birth')
    op.drop_column('student_profiles', 'email')
    # ### end Alembic commands ###
