"""add priority category icon to announcements

Revision ID: 49fc8fab8732
Revises: 062b20144f7a
Create Date: 2025-10-11 01:13:28.375963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49fc8fab8732'
down_revision: Union[str, Sequence[str], None] = '062b20144f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('priority', sa.String(), nullable=False))
    op.add_column('announcements', sa.Column('category', sa.String(), nullable=False))
    op.add_column('announcements', sa.Column('icon', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'icon')
    op.drop_column('announcements', 'category')
    op.drop_column('announcements', 'priority')
    # ### end Alembic commands ###
