"""add_servsafe_certificate_url_to_student_profile

Revision ID: 962bafc27a50
Revises: 16348e50a45d
Create Date: 2025-10-10 14:43:21.133743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '962bafc27a50'
down_revision: Union[str, Sequence[str], None] = '16348e50a45d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('servsafe_certificate_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'servsafe_certificate_url')
    # ### end Alembic commands ###
