"""add_array_fields_to_announcements

Revision ID: 974438272a1f
Revises: ac07f9393191
Create Date: 2025-10-17 00:23:21.089526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '974438272a1f'
down_revision: Union[str, Sequence[str], None] = 'ac07f9393191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('target_program_stages', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('announcements', sa.Column('target_locations', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'target_locations')
    op.drop_column('announcements', 'target_program_stages')
    # ### end Alembic commands ###
