"""add_is_private_field_to_posts

Revision ID: a5763a5b0bb7
Revises: 974438272a1f
Create Date: 2025-10-19 13:29:32.571688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5763a5b0bb7'
down_revision: Union[str, Sequence[str], None] = '974438272a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_private')
    # ### end Alembic commands ###
