"""update_default_bucket_to_pre_apprentice_explorer

Revision ID: ac07f9393191
Revises: bbdc25f153fb
Create Date: 2025-10-16 22:31:41.341099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac07f9393191'
down_revision: Union[str, Sequence[str], None] = 'bbdc25f153fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
