"""add_ccap_connection_to_student_profile

Revision ID: bbdc25f153fb
Revises: 49fc8fab8732
Create Date: 2025-10-16 15:46:50.216510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbdc25f153fb'
down_revision: Union[str, Sequence[str], None] = '49fc8fab8732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('ccap_connection', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'ccap_connection')
    # ### end Alembic commands ###
