"""add culinary_teacher to student_profile

Revision ID: c79a77b520e9
Revises: b1c251ef82bc
Create Date: 2026-01-30 16:27:02.340131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c79a77b520e9'
down_revision: Union[str, Sequence[str], None] = 'b1c251ef82bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('culinary_teacher', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'culinary_teacher')
    # ### end Alembic commands ###
